import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const legacyPath = path.resolve(__dirname, '../../legacy/index.html');
const outStructure = path.resolve(__dirname, '../../frontend/src/data/summary-structure.js');
const outDirAr = path.resolve(__dirname, '../../frontend/src/locales/ar');
const outDirFr = path.resolve(__dirname, '../../frontend/src/locales/fr');
const outDirEn = path.resolve(__dirname, '../../frontend/src/locales/en');

const html = fs.readFileSync(legacyPath, 'utf8');

function extractBlock(varName, openChar) {
  const closeChar = openChar === '[' ? ']' : '}';
  const re = new RegExp(`const\\s+${varName}\\s*=\\s*\\${openChar}`);
  const m = html.match(re);
  if (!m) throw new Error(`${varName} not found`);
  const start = m.index + m[0].length - 1;
  let depth = 0;
  let inString = false;
  let stringChar = null;
  let escape = false;
  let backtick = false;
  for (let i = start; i < html.length; i++) {
    const c = html[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (inString) {
      if (c === '\\') escape = true;
      else if (c === stringChar) inString = false;
      continue;
    }
    if (c === '"' || c === "'" || c === '`') {
      inString = true;
      stringChar = c;
      continue;
    }
    if (c === openChar) depth++;
    else if (c === closeChar) {
      depth--;
      if (depth === 0) return html.slice(start, i + 1);
    }
  }
  throw new Error(`${varName} unterminated`);
}

const sandbox = {};
vm.createContext(sandbox);

const sumLit = extractBlock('SUM_STRUCTURE', '{');
const cardsLit = extractBlock('CARDS_HTML', '{');

const SUM_RAW = vm.runInContext('(' + sumLit + ')', sandbox);
const CARDS_HTML = vm.runInContext('(' + cardsLit + ')', sandbox);

// Convert numeric-keyed object to array for easier iteration in React
const SUM_STRUCTURE = Object.keys(SUM_RAW)
  .sort((a, b) => Number(a) - Number(b))
  .map((k) => SUM_RAW[k]);

fs.mkdirSync(path.dirname(outStructure), { recursive: true });
fs.writeFileSync(
  outStructure,
  `// Auto-generated by backend/scripts/extract-theory.js\nexport const SUM_STRUCTURE = ${JSON.stringify(SUM_STRUCTURE, null, 2)};\n`,
  'utf8'
);

fs.mkdirSync(outDirAr, { recursive: true });
fs.mkdirSync(outDirFr, { recursive: true });
fs.mkdirSync(outDirEn, { recursive: true });

fs.writeFileSync(path.join(outDirAr, 'theory.json'), JSON.stringify(CARDS_HTML, null, 2), 'utf8');
const stubs = Object.fromEntries(Object.keys(CARDS_HTML).map((k) => [k, null]));
fs.writeFileSync(path.join(outDirFr, 'theory.json'), JSON.stringify(stubs, null, 2), 'utf8');
fs.writeFileSync(path.join(outDirEn, 'theory.json'), JSON.stringify(stubs, null, 2), 'utf8');

console.log(
  `✓ Extracted structure (${SUM_STRUCTURE.length} axes) and ${Object.keys(CARDS_HTML).length} theory cards`
);
